# Site setings
name: 'Vadim Komisarchik'
description: 'My Thoughts'
meta_description: 'Vadim Komisarchiik - Engineering Manager at Freshly'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'vadim.JPG'
  greetings: "I work as the mobile Engineering Manager at Freshly."
favicon: 'assets/images/favicon.png'
baseurl:
production_url: https://talman.io
disqus:
mailchimp_url: 
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: vadim@myclok.com
contact_page_description: "Get in touch by using the form below."
thankyou_page_description: "Your message has been successfully sent. I will contact you very soon!"

# Social links
twitter: 'vkomissarchik'
github: 'Vadimkomis'
linkedin: 'vadimkomisarchik'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Publications and Talks
    url: /publications
  - text: Software and Data
    url: /software
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
